[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "proxmox-mcp"
version = "0.1.0"
description = "A Model Context Protocol server for interacting with Proxmox hypervisors"
requires-python = ">=3.10"
authors = [
    {name = "Kevin", email = "kevin@example.com"}
]
readme = "README.md"
license = {text = "MIT"}
keywords = ["proxmox", "mcp", "virtualization", "cline", "qemu", "lxc"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Systems Administration",
]

dependencies = [
    "mcp @ git+https://github.com/modelcontextprotocol/python-sdk.git",
    "proxmoxer>=2.0.1,<3.0.0",
    "requests>=2.32.4",
    "urllib3>=2.5.0,<3.0.0",
    "pydantic>=2.0.0,<3.0.0",
    "cryptography>=45.0.0,<46.0.0",
    "claude-code-sdk>=0.0.10,<1.0.0",
    "setuptools>=78.1.1",
]

[project.optional-dependencies]
dev = [
    # Testing
    "pytest>=7.0.0,<9.0.0",
    "pytest-asyncio>=0.21.0,<1.1.0",
    "pytest-cov>=4.0.0,<7.0.0",

    # Code formatting and linting
    "black>=23.0.0,<26.0.0",
    "ruff>=0.1.0,<0.13.0",

    # Type checking
    "mypy>=1.0.0,<2.0.0",
    "types-requests>=2.31.0,<3.0.0",

    # Security tools (addresses Codacy security issues)
    "bandit>=1.7.0,<2.0.0",
    "safety>=3.0.0,<4.0.0",

    # Code quality tools
    "yamllint>=1.32.0,<2.0.0",
    "radon>=6.0.0,<7.0.0",  # Complexity analysis

    # Pre-commit
    "pre-commit>=3.0.0,<5.0.0",
]

[project.urls]
Homepage = "https://github.com/yourusername/proxmox-mcp"
Documentation = "https://github.com/yourusername/proxmox-mcp#readme"
Repository = "https://github.com/yourusername/proxmox-mcp.git"
Issues = "https://github.com/yourusername/proxmox-mcp/issues"

[project.scripts]
proxmox-mcp = "proxmox_mcp.server:main"

[tool.pytest.ini_options]
asyncio_mode = "strict"
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
exclude = "mem0-mcp/"

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = []

[tool.ruff.lint.isort]
force-sort-within-sections = true
known-first-party = ["proxmox_mcp"]
known-third-party = ["mcp", "proxmoxer", "pydantic", "cryptography", "requests"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
split-on-trailing-comma = true


[[tool.uv.index]]
name = "safety"
url = "https://pkgs.safetycli.com/repository/the-mothership/project/proxmoxmcp/pypi/simple/"
default = false
[dependency-groups]
dev = [
    "ruff>=0.1.15",
]
