name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      # Cache UV virtual environment
      - name: Cache UV venv
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Install dependencies
        run: uv sync --extra dev

      # Use ruff for both linting and formatting
      - name: Run ruff linting with auto-fix
        run: uv run ruff check . --fix-only --exit-zero

      - name: Run ruff formatting
        run: uv run ruff format .

      - name: Auto-fix YAML spacing issues
        run: |
          ./scripts/yaml-autofix.sh || true

      - name: Run security checks
        run: uv run bandit -r src/ --format custom --skip B101,B601

      # Apply all fixes - this must be the last step
      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
