name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      # Cache UV virtual environment
      - name: Cache UV venv
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Install dependencies
        run: |
          echo "Installing dependencies with uv..."
          uv sync --extra dev || {
            echo "uv sync failed, trying pip fallback..."
            python -m pip install -e ".[dev]" || {
              echo "pip install failed, installing minimal ruff for formatting..."
              python -m pip install ruff
            }
          }
          echo "Dependencies installed successfully"

      # Use ruff for both linting and formatting
      - name: Run ruff linting with auto-fix
        run: |
          echo "Running ruff linting with auto-fix..."
          if command -v uv >/dev/null 2>&1; then
            uv run ruff check . --fix-only --exit-zero
          else
            python -m ruff check . --fix-only --exit-zero
          fi
          echo "Ruff linting completed"

      - name: Run ruff formatting
        run: |
          echo "Running ruff formatting..."
          if command -v uv >/dev/null 2>&1; then
            uv run ruff format .
          else
            python -m ruff format .
          fi
          echo "Ruff formatting completed"

      - name: Auto-fix YAML spacing issues
        run: |
          echo "Auto-fixing YAML spacing issues..."
          ./scripts/yaml-autofix.sh || true
          echo "YAML auto-fix completed"

      - name: Run security checks
        run: |
          echo "Running security checks..."
          uv run bandit -r src/ --format custom --skip B101,B601 || {
            echo "Warning: Security checks failed or bandit not available"
            echo "This is non-blocking for formatting fixes"
          }

      # Apply all fixes - this must be the last step
      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
